### ISSUE TITLE
[DESIGN] Rapport de test Wall Run

### ISSUE THREAD

**Issue by Hask0ll** [OutcastsGameStudio/SR#117]
Tester le Wall Run pour avoir une idée des valeurs à modifier

_Critaire d'acceptance:_

- [x] Doc Rapport
- [x] Valeurs disponible

**Comment by Arcagon** [comment]
J'ai test le WallRun dans la gym

-Il faut corriger la vitesse du personnage, on ne peut pas la changer

-Il y a toujours le bug, quand on rentre dans le mur tout droit on l'escalade au lieu de tomber

-Il y a toujours le déplacement en l'air avec les touches

-Lorsque que le saut depuis un wall run on est pas assez propulsé vers l'opposé du mur

-Parfois en essayant de faire un wall run, on se trouve coller à un mur sans bouger au lieu de tomber
