### ISSUE TITLE
[TEXTURE] Pipe_Tuyaux

### ISSUE THREAD

**Issue by Pennywise3838** [OutcastsGameStudio/SR#86]
_Faire les textures des tuyaux modular_

Critères d'acceptances :

- [x] Textures
- [x] import UE
- [x] mis sur les props
- [x] création bp opérationnel

**Comment by tomvarichon** [comment]
![Image](https://github.com/user-attachments/assets/0969b365-01c7-45a1-bb3b-4b5bd366b699)
![Image](https://github.com/user-attachments/assets/96a59fca-bac3-4eeb-b424-cd8dce1b9178)
